services:
  api:
    build: ./modelo1/api
    ports:
      - "5000:80"
  react:
    build: ./modelo1/react-app
    ports:
      - "3000:3000"
  bootstrap:
    build: ./modelo2
    ports:
      - "8000:80"
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=marcos
      - POSTGRES_USER=marcos
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"