CREATE TABLE IF NOT EXISTS Usuarios (
    Id SERIAL NOT NULL PRIMARY KEY,
    Nome VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Senha VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tokens (
    Id SERIAL NOT NULL PRIMARY KEY,
    IdUsuario INT NOT NULL,
    Token VARCHAR(255) NOT NULL,
    ExpiracaoToken TIMESTAMP NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(Id) ON DELETE CASCADE
);